name: ğŸ§Š GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: '0 18 * * *'  # æ¯å¤©é‹è¡Œ
  workflow_dispatch:       # å…è¨±æ‰‹å‹•åŸ·è¡Œ

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate GitHub Contributions (south-season-animate)
    steps:
      - uses: actions/checkout@v4

      - name: Generate GitHub Profile 3D (south-season-animate)
        uses: yoshi389111/github-profile-3d-contrib@0.9.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: zhu7055
        with:
          args: --theme "Southern Hemisphere"

      - name: Commit and push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "ğŸŒ™ generated"
          git push
